### ISSUE TITLE
Update lambdas

### ISSUE THREAD

**Issue by axelheer** [cezarypiatek/MappingGenerator#102]
Is there a way to complete lambdas too?

```csharp
var result = context.Personen.Save(key, person =>
{
    |
});
```

A workaround would be to extract an update method first:

```csharp
var result = context.Personen.Save(key, person =>
{
    Update(item, person);
});
```

And then let *MappingGenerator* do its magic within `Update`.

Having this magic within the lambda itself would come in very handy.

**Comment by cezarypiatek** [comment]
Hi, can you provide an example of the expected code that should be generated?

**Comment by axelheer** [comment]
```cs
var result = context.Personen.Save(key, person =>
{
    person.X = item.X;
    person.Y = item.Y;
});
```

**Comment by cezarypiatek** [comment]
Here's a pre-release version with the implementation of the requested feature https://ci.appveyor.com/api/buildjobs/8v29nu5lhugmgo5h/artifacts/MappingGenerator%2FMappingGenerator%2FMappingGenerator.Vsix%2Fbin%2FRelease%2FMappingGenerator.vsix

![image](https://user-images.githubusercontent.com/7759991/73127630-86be1c00-3fc3-11ea-8c6c-4452cfb1e111.png)

It also contains a couple of improvements for #101 

Please let me know if everything works according to your expectations.

**Comment by axelheer** [comment]
#102 as well as #101 work like a charm!

I've deleted some mapping code and was able to re-generate it using your tool. Except some business logic, calculations, aggregations and the like... of course. That should be a huge "dull-saver"!

Thanks a lot, I'm pumped. 😲

**Comment by cezarypiatek** [comment]
I've just made an official release with #102 and #101. Please install a new version from the marketplace to make sure you will get automatic updates/notifications in the furture. https://marketplace.visualstudio.com/items?itemName=54748ff9-45fc-43c2-8ec5-cf7912bc3b84.mappinggenerator
