### ISSUE TITLE
Incorrect mapping for structs from dll

### ISSUE THREAD

**Issue by alec-anikin** [cezarypiatek/MappingGenerator#104]
Hi!

It works fine for structs declared in solution but not for external structs.
VS2019, SDK 3.1.102

How to reproduce:
```
using System.Drawing;
using MappingGenerator.OnBuildGenerator;
namespace Test
{
    [MappingInterface]
    public interface IMapper
    {
        SomeClass Map(SomeClass other);
    }
    
    public sealed class SomeClass
    {
        public Point SomeStruct { get; }
        
        public SomeClass(Point someStruct)
        {
            SomeStruct = someStruct;
        }
    }
}
```

Generated mapping
```
public partial class Mapper : Test.IMapper
    {
        public virtual SomeClass Map(SomeClass other)
        {
            return new Protobuf.SomeClass(someStruct: new Point());
        }
    }
```

Thank you!

**Comment by cezarypiatek** [comment]
Just to be sure, the expected mapping code should be as follows? 

```csharp
public partial class Mapper : Test.IMapper
    {
        public virtual SomeClass Map(SomeClass other)
        {
            return new Protobuf.SomeClass(someStruct: other.SomeStruct);
        }
    }
```

**Comment by alec-anikin** [comment]
For project declared structs now mapping is
```
public partial class Mapper : Protobuf.IMapper
    {
        public virtual SomeClass Map(SomeClass other)
        {
            return new Protobuf.SomeClass(someStruct: new Protobuf.SomeStruct(value: other.SomeStruct.Value));
        }
    }
```
I think both versions are correct: `someStruct: new Protobuf.SomeStruct(value: other.SomeStruct.Value)` or `someStruct: other.SomeStruct` but the second one is simpler especially for multiple constructors cases.

**Comment by cezarypiatek** [comment]
@alec-anikin can you show the definition of the `Point` structure? The version from the external library. Does it contain fields or properties?

**Comment by cezarypiatek** [comment]
I've just tested it with MappingGenerator.OnBuildGenerator 1.13.329 and SmartCodeGenerator.Engine 1.2.9 and I've got the mapping code as follows

```csharp
// ------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
// ------------------------------------------------------------------------------
using System;
using System.Diagnostics;
using System.Drawing;
using MappingGenerator.OnBuildGenerator;
using System.Linq;
using ConsoleApp11;

namespace ConsoleApp11
{
    [System.CodeDom.Compiler.GeneratedCode("MappingGenerator.OnBuildGenerator.OnBuildMappingGenerator", "1.13.329.0")]
    public partial class Mapper : ConsoleApp11.IMapper
    {
        public virtual SomeClass Map(SomeClass other)
        {
            return new ConsoleApp11.SomeClass(someStruct: new Point(x: other.SomeStruct.X, y: other.SomeStruct.Y));
        }
    }
}
```
It looks like it's working as expected. Can you send me a solution that reproduces that problem?

**Comment by alec-anikin** [comment]
It sounds very strange but just add reference to another project from solution and generated code will be broken.

**Comment by cezarypiatek** [comment]
Ok, I'm able to reproduce the issue but it completely doesn't make any sense to me. Removing reference to Lib project fixes the issue. I need to take a look closer to what's going there.

**Comment by cezarypiatek** [comment]
It looks like `Microsoft.CodeAnalysis.MSBuild.MSBuildWorkspace` (which is used for loading projects) doesn't play very well with `netstandard` projects. I've made a small test by replacing `MSBuildWorkspace` with https://github.com/daveaglick/Buildalyzer#roslyn-workspaces and it seems to solve the issue but I don't know what the ramifications could be.  I need to run a couple more tests to make sure that there are no negative side effects.

**Comment by cezarypiatek** [comment]
Waiting for response https://github.com/daveaglick/Buildalyzer/issues/130

**Comment by cezarypiatek** [comment]
@alec-anikin 
A new version of `SmartCodeGenerator.Engine` has been released. Please update the `SmartCodeGenerator.Engine` package and verify if it works correctly.

**Comment by alec-anikin** [comment]
It works fine! Thank you!
