### ISSUE TITLE
not support fields?

### ISSUE THREAD

**Issue by raveneer** [cezarypiatek/MappingGenerator#105]
I know using {get; private set;} is better than using a field in C# culture.
but just have curious.

**Comment by cezarypiatek** [comment]
Hi, currently fields are not supported. I'm working on it but I can't promise when this will be released (I need to refactor a couple of things before to keep the codebase still maintainable).  The same issue has been reported as #94

**Comment by cezarypiatek** [comment]
Close reason: duplicated #94
