### ISSUE TITLE
[Documentation] ReSharper Settings

### ISSUE THREAD

**Issue by michha** [cezarypiatek/MappingGenerator#107]
ReSharper seems to have moved the related settings (version 2019.3).
![ReSharper Settings](https://user-images.githubusercontent.com/10424767/77153577-44342f80-6a9a-11ea-8c51-ad9003d9f49b.png)

Its probably the best to let the user search for term "bulb" in his ReSharper settings to find the options.
![ReSharper Settings bulb](https://user-images.githubusercontent.com/10424767/77153579-45fdf300-6a9a-11ea-8ca7-ce84d7bb7b22.png)

**Comment by cezarypiatek** [comment]
Thanks, I've updated the documentation
