### ISSUE TITLE
VS Code support may now be possible?

### ISSUE THREAD

**Issue by ericsampson** [cezarypiatek/MappingGenerator#111]
Does this help address the [original issue](https://github.com/cezarypiatek/MappingGenerator/issues/83#issuecomment-543298726_) that was preventing VS Code support?
https://github.com/dotnet/roslyn/pull/35685
https://www.strathweb.com/2019/04/roslyn-analyzers-in-code-fixes-in-omnisharp-and-vs-code/

I really like MappingGenerator, but a lot of my colleagues are running Mac/VSCode, so until Code works we won't be able to adopt it more widely unfortunately : (

Cheers,
Eric

**Comment by cezarypiatek** [comment]
Hi, this article is about roslyn analyzers. MappingGenerator is built as code refactoring and link to the instruction on how to install code refactorings to VSCode has been provided in the mentioned issue.
https://www.strathweb.com/2017/05/using-roslyn-refactorings-with-omnisharp-and-visual-studio-code/
