### ISSUE TITLE
Feature request: support inheritance hierarchy flattening 

### ISSUE THREAD

**Issue by otryshko** [cezarypiatek/MappingGenerator#113]
Hi,
In my runtime object-to-storage Dto convertion I need to represent my class hierarchy with a "Type" property, i.e.
```
public class StorageDto{
  public string Type {get;set;}
  public sting Shared {get;set;}
  public string PropA {get;set;}
  public string PropB {get;set;}
}
public class RuntimeDtoBase{
  public sting Shared {get;set;}
}
public class RuntimeDtoA : RuntimeDtoBase{
  public string PropA {get;set;}
}
public class RuntimeDtoB : RuntimeDtoBase{
  public string PropB {get;set;}
}
```
Can I make the Mapping Generator to generate (for RuntimeDto -> StorageDto codepath) 
```
var target = new StorageDto(); target.Type = typeof(source.Type)
```
and (for StorageDto -> RuntimeDto codepath) 
```
if (source.Type == typeof(RuntimeDtoA)
{
  target = new RuntimeDtoA();
  ...
}
else if (source.Type == typeof(RuntimeDtoB)
{
  target = new RuntimeDtoB();
  ...
}

**Comment by cezarypiatek** [comment]
Hi,

It looks like a very custom logic. If you have multiple mapping pairs: (RuntimeDtoA, StorageDto), (RuntimeDtoB, StorageDto) then you should prepare an empty method for each pair and then use MappingGenerator to generate them. A method responsible for deciding which specific mapping method to invoked should be implemented manually.
