### ISSUE TITLE
Conditional mapping

### ISSUE THREAD

**Issue by spmoran-blazor** [cezarypiatek/MappingGenerator#114]
Hi. How can we do condition mapping to handle nulls into a dto? Is there any real documentation?

**Comment by cezarypiatek** [comment]
Hi,
Can you provide a sample definition of the source and destination types and expected mapping code as well?

**Comment by spmoran-blazor** [comment]
This was more about how to handle nulls inside nested objects. I decided to do null checks in the objects and and set variables based on the results instead of directly referencing entity.whatever. That works fine. You can close this if you like. Thanks for this great tool!
