### ISSUE TITLE
Crashing Quick Actions and Refactoring of Visual Studio 16.6

### ISSUE THREAD

**Issue by carlospence** [cezarypiatek/MappingGenerator#123]
I just updated to Visual Studio 16.6 and the Quick Actions stopped working, anytime I click on the Quick Actions the error below is displayed. I have update the MappingGenerator to the latest version and still having the same issue. Whenever I disable the plugin, every works as expected.

![MappingGenerator Error](https://user-images.githubusercontent.com/12647064/82815771-c45b8480-9e91-11ea-9f22-3a9acd9f6f0b.PNG)

**Comment by cezarypiatek** [comment]
Hi,

Did you try to restart VS/OS ? Please also try to clear MEF cache with this extension https://marketplace.visualstudio.com/items?itemName=MadsKristensen.ClearMEFComponentCache

Please let me know if that solved the issue.

**Comment by mrdavidkovacs** [comment]
Hi,

I have the same problem.

Things I've tried:
- cleared MEF Component cache
- reinstalled the extension
- cleared the temp folder (as suggested)

Nevertheless, I get to following exception: `Microsoft.VisualStudio.ExtensibilityHosting.InvalidMEFCacheException: The Visual Studio component cache is out of date (assembly: MappingGenerator, Version=1.14.356.0, Culture=neutral, PublicKeyToken=null). Please restart Visual Studio.&#x000D;&#x000A;   at Microsoft.VisualStudio.ExtensibilityHosting.FaultCatchingAssemblyLoader.&lt;&gt;c__DisplayClass17_0.&lt;LoadAssembly&gt;b__0(AssemblyName assemblyNameParam)&#x000D;&#x000A;   at Microsoft.VisualStudio.ExtensibilityHosting.Utilities.SafeGetOrAdd[TKey,TValue](IDictionary`2 dictionary, TKey key, Object lockObj, Func`2 valueFactory)&#x000D;&#x000A;   at Microsoft.VisualStudio.ExtensibilityHosting.FaultCatchingAssemblyLoader.LoadAssembly(AssemblyName assemblyName)&#x000D;&#x000A;   at Microsoft.VisualStudio.Composition.Reflection.ResolverExtensions.GetManifest(Resolver resolver, AssemblyName assemblyName)&#x000D;&#x000A;   at Microsoft.VisualStudio.Composition.Reflection.ResolverExtensions.TryUseFastReflection(TypeRef typeRef, Module&amp; manifest)&#x000D;&#x000A;   at Microsoft.VisualStudio.Composition.Reflection.ResolverExtensions.Resolve(MethodRef methodRef)&#x000D;&#x000A;   at Microsoft.VisualStudio.Composition.Reflection.MethodRef.Resolve()&#x000D;&#x000A;   at Microsoft.VisualStudio.Composition.RuntimeExportProviderFactory.RuntimeExportProvider.RuntimePartLifecycleTracker.CreateValue()&#x000D;&#x000A;   at Microsoft.VisualStudio.Composition.ExportProvider.PartLifecycleTracker.Create()&#x000D;&#x000A;   at Microsoft.VisualStudio.Composition.ExportProvider.PartLifecycleTracker.MoveNext(PartLifecycleState nextState)&#x000D;&#x000A;   at Microsoft.VisualStudio.Composition.ExportProvider.PartLifecycleTracker.MoveToState(PartLifecycleState requiredState)&#x000D;&#x000A;   at Microsoft.VisualStudio.Composition.ExportProvider.PartLifecycleTracker.GetValueReadyToExpose()&#x000D;&#x000A;   at Microsoft.VisualStudio.Composition.RuntimeExportProviderFactory.RuntimeExportProvider.&lt;&gt;c__DisplayClass15_0.&lt;GetExportedValueHelper&gt;b__0()&#x000D;&#x000A;--- End of stack trace from previous location where exception was thrown ---&#x000D;&#x000A;   at Microsoft.VisualStudio.Composition.RuntimeExportProviderFactory.RuntimeExportProvider.&lt;&gt;c__DisplayClass15_0.&lt;GetExportedValueHelper&gt;b__0()&#x000D;&#x000A;   at Microsoft.VisualStudio.Composition.DelegateServices.&lt;&gt;c__DisplayClass2_0`1.&lt;As&gt;b__0()&#x000D;&#x000A;   at System.Lazy`1.CreateValue()&#x000D;&#x000A;   at System.Lazy`1.LazyInitValue()&#x000D;&#x000A;   at System.Lazy`1.get_Value()&#x000D;&#x000A;   at Microsoft.CodeAnalysis.CodeRefactorings.CodeRefactoringService.&lt;&gt;c__DisplayClass5_0.&lt;DistributeLanguages&gt;b__0()&#x000D;&#x000A;   at System.Lazy`1.CreateValue()&#x000D;&#x000A;   at System.Lazy`1.LazyInitValue()&#x000D;&#x000A;   at System.Lazy`1.get_Value()&#x000D;&#x000A;   at Microsoft.CodeAnalysis.CodeRefactorings.CodeRefactoringService.&lt;&gt;c.&lt;.ctor&gt;b__4_4(Lazy`2 lz)&#x000D;&#x000A;   at System.Linq.Enumerable.WhereSelectListIterator`2.MoveNext()&#x000D;&#x000A;   at System.Linq.Buffer`1..ctor(IEnumerable`1 source)&#x000D;&#x000A;   at System.Linq.Enumerable.ToArray[TSource](IEnumerable`1 source)&#x000D;&#x000A;   at System.Collections.Immutable.ImmutableArray.CreateRange[T](IEnumerable`1 items)&#x000D;&#x000A;   at System.Collections.Immutable.ImmutableArray.ToImmutableArray[TSource](IEnumerable`1 items)&#x000D;&#x000A;   at Microsoft.CodeAnalysis.CodeRefactorings.CodeRefactoringService.&lt;&gt;c__DisplayClass4_1.&lt;.ctor&gt;b__3()&#x000D;&#x000A;   at System.Lazy`1.CreateValue()&#x000D;&#x000A;--- End of stack trace from previous location where exception was thrown ---&#x000D;&#x000A;   at System.Lazy`1.get_Value()&#x000D;&#x000A;   at Microsoft.CodeAnalysis.CodeRefactorings.CodeRefactoringService.GetProviders(Document document)&#x000D;&#x000A;   at Microsoft.CodeAnalysis.CodeRefactorings.CodeRefactoringService.&lt;GetRefactoringsAsync&gt;d__12.MoveNext()&#x000D;&#x000A;--- End of stack trace from previous location where exception was thrown ---&#x000D;&#x000A;   at Roslyn.Utilities.TaskExtensions.WaitAndGetResult_CanCallOnBackground[T](Task`1 task, CancellationToken cancellationToken)&#x000D;&#x000A;   at Microsoft.CodeAnalysis.Editor.Implementation.Suggestions.SuggestedActionsSourceProvider.SuggestedActionsSource.GetRefactorings(ITextBufferSupportsFeatureService supportsFeatureService, ISuggestedActionCategorySet requestedActionCategories, Workspace workspace, Document document, Nullable`1 selectionOpt, Func`2 addOperationScope, CancellationToken cancellationToken)&#x000D;&#x000A;   at Microsoft.CodeAnalysis.Editor.Implementation.Suggestions.SuggestedActionsSourceProvider.SuggestedActionsSource.GetSuggestedActions(ISuggestedActionCategorySet requestedActionCategories, SnapshotSpan range, IUIThreadOperationContext operationContext, CancellationToken cancellationToken)&#x000D;&#x000A;   at Microsoft.CodeAnalysis.Editor.Implementation.Suggestions.SuggestedActionsSourceProvider.SuggestedActionsSource.GetSuggestedActions(ISuggestedActionCategorySet requestedActionCategories, SnapshotSpan range, IUIThreadOperationContext operationContext)&#x000D;&#x000A;   at Microsoft.VisualStudio.Language.Intellisense.Implementation.LightBulbSession.&lt;&gt;c__DisplayClass40_4.&lt;TryGetSuggestedActionSets&gt;b__1()&#x000D;&#x000A;   at Microsoft.VisualStudio.Text.Utilities.GuardedOperations.CallExtensionPoint[T](Object errorSource, Func`1 call, T valueOnThrow, Predicate`1 exceptionToIgnore, Predicate`1 exceptionToHandle)&#x000D;&#x000A;--- End of stack trace from previous location where exception was thrown ---&#x000D;&#x000A;   at Microsoft.VisualStudio.Telemetry.WindowsErrorReporting.WatsonReport.GetClrWatsonExceptionInfo(Exception exceptionObject)`

Funny is that the exception states that I have the version 1.14.356.0 installed.
But I definitely have the version 1.16.405 installed (downloaded from the GitHub releases page).

**Comment by cezarypiatek** [comment]
Thanks. I've just reported this issue to Microsoft. I will provide a link to the ticket when I get confirmation.

**Comment by cezarypiatek** [comment]
https://developercommunity.visualstudio.com/content/problem/1080611/the-visual-studio-component-cache-is-out-of-date-2.html

**Comment by cezarypiatek** [comment]
@carlospence @mrdavidkovacs is it still an issue with the latest MappingGenerator and VS 16.7.2?

**Comment by mrdavidkovacs** [comment]
@cezarypiatek 
It worked for me yesterday using the latest version of the extension and Visual Studio 16.7.2.
Thank you very much.
