### ISSUE TITLE
Support for JetBrain's Rider IDE

### ISSUE THREAD

**Issue by Wndrr** [cezarypiatek/MappingGenerator#126]
I've moved away from Visual studio a while back and am really interested in the features offered by your plugin. Are there any plans to port to Rider 2020 at any point in the future ?

If not, are you open to pull requests enabling such support ?

**Comment by cezarypiatek** [comment]
Hi,

Rider is supported by installing MappingGenerator as a nugget package. This is the only way that I know to use Roslyn analyzers/code fixes/refactorings in Rider. If you know something more then I'm of course open to suggestions or pull requests.

https://www.nuget.org/packages/MappingGenerator/
