### ISSUE TITLE
NullReferenceException on omitted type parameter

### ISSUE THREAD

**Issue by NoahStahl** [cezarypiatek/MappingGenerator#138]
I encountered an issue with a particular case that seems to cause an exception. When entering this line, as example:

```
var test = new HashSet();
```

The exception below is thrown. It specifically seems to happen when forgetting the angle brackets and type parameter. Occurs in empty console app, no other conditions or dependencies involved as far as I can tell.

Here's a [short video](https://www.screencast.com/t/Yy9MElfu4y1) of the issue. Version 1.17.442 on VS 2019 16.7.3. Thanks!

> System.NullReferenceException: Object reference not set to an instance of an object.at MappingGenerator.MethodHelpers.ConstructorInvocation.GetOverloadParameterSets(SemanticModel semanticModel)at MappingGenerator.Features.Suggestions.MethodParametersSuggestionProvider.GetArgumentListWithLocalVariables(Document document, IInvocation invocation, Boolean generateNamedParameters, SemanticModel semanticModel)at MappingGenerator.Features.Suggestions.MethodParametersSuggestionProvider.SuggestMethodParameters(CompletionContext context, IInvocation invocation, SemanticModel semanticModel)at MappingGenerator.Features.Suggestions.MethodParametersSuggestionProvider.<ProvideCompletionsAsync>d__3.MoveNext() --- End of stack trace from previous location where exception was thrown --- at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)at Microsoft.CodeAnalysis.Completion.CompletionServiceWithProviders.<GetContextAsync>d__35.MoveNext() --- End of stack trace from previous location where exception was thrown --- at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)at Microsoft.CodeAnalysis.Completion.CompletionServiceWithProviders.<ComputeNonEmptyCompletionContextsAsync>d__29.MoveNext() --- End of stack trace from previous location where exception was thrown --- at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)at System.Runtime.CompilerServices.TaskAwaiter.ValidateEnd(Task task)at Microsoft.CodeAnalysis.Completion.CompletionServiceWithProviders.<GetCompletionsWithAvailabilityOfExpandedItemsAsync>d__26.MoveNext() --- End of stack trace from previous location where exception was thrown --- at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)at System.Runtime.CompilerServices.TaskAwaiter.ValidateEnd(Task task)at Microsoft.CodeAnalysis.Editor.Implementation.IntelliSense.AsyncCompletion.CompletionSource.<GetCompletionContextWorkerAsync>d__25.MoveNext() --- End of stack trace from previous location where exception was thrown --- at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)at Microsoft.VisualStudio.Text.Utilities.GuardedOperations.<CallExtensionPointAsync>d__36`1.MoveNext() --- End of stack trace from previous location where exception was thrown --- at Microsoft.VisualStudio.Telemetry.WindowsErrorReporting.WatsonReport.GetClrWatsonExceptionInfo(Exception exceptionObject)

**Comment by cezarypiatek** [comment]
Hi @NoahStahl 
Thanks for reporting this issue. I will let you know when the fix is ready.

**Comment by cezarypiatek** [comment]
Should be fixed in 1.18.448. Would you mind to test it and let me know if the problem disappeared?

**Comment by NoahStahl** [comment]
Thanks! The issue appears resolved once I upgraded to 1.18.448.

**Comment by cezarypiatek** [comment]
Thanks for verification
