### ISSUE TITLE
Generate mapping code for Expression<Func<fromType, toType>>

### ISSUE THREAD

**Issue by Serguzest** [cezarypiatek/MappingGenerator#14]
Hello, 

Thanks for the great project. We even [once had tweeting](https://twitter.com/cezary_piatek/status/960890224556601344) about the particular subject before and agreed need of kind of project.

This is a common pattern in my coding which allows me to use the projection in Entity Framework queries.

I think it is a good idea to support that particular use case.

```
public fromType{
        ....
        public static Expression<Func<fromType, toType>> Projection = (ft) => 
             new toType{
                .....
            };
}
```

**Comment by cezarypiatek** [comment]
As I understand you need to generate mapping expression instead of mapping function, right? 

Please check the mapping rules https://github.com/cezarypiatek/MappingGenerator#mapping-rules and tell me which of them are supported by EntityFramework (probably not all constructions can be translated into underlying SQL).

**Comment by Serguzest** [comment]
Nested properties and and collections are supported. But I don't think you should care about EF though.

My idea is: when your rosyln analyzer sees the pattern 

`Expression<Func<T,T2>>  = (T) => new T2{}`
or
`Func<T,T2> = (T) => new T2{}`

It can populate mapping code for T --> T2 with same rules you were using for regular methods.

**Comment by cezarypiatek** [comment]
I've managed to make it work. I need few more days to test it and then I will release a new version.
Efect looks as follows
![lambda_mapping](https://user-images.githubusercontent.com/7759991/41869113-4704c6f0-78b8-11e8-8c3c-47a6b5bf308c.gif)

**Comment by cezarypiatek** [comment]
Available in https://github.com/cezarypiatek/MappingGenerator/releases/tag/1.3.116
@Serguzest I would be appreciate if you could check this new mapping option and let me know if everything works fine.

**Comment by Serguzest** [comment]
Sorry for the late reply.

I was testing it on a real project. It got stuck on a model and visual studio restarted itself.  It is probably a circular referencing issue. 

I isolated the problem for reproducing.

```
  public class Model1Vm {
        public int Id { get; set; }
        public List<Model2Vm> Model2s { get; set; }
        public Expression<Func<Model1, Model1Vm>> Projection = (m) => new Model1Vm {

        };
    }

    public class Model2Vm {
        public int Id { get; set; }
        public Model1Vm Model1 { get; set; }
    }

    public class Model1 {
        public int Id { get; set; }
        public List<Model2> Model2s { get; set; }
    }

    public class Model2 {
        public int Id { get; set; }
        public Model1 Model1 { get; set; }
    }
```

**Comment by cezarypiatek** [comment]
How do you imagine mapping code for this circular model?

**Comment by Serguzest** [comment]
Circular object referencing is a common thing between EF entity types but I don't know if it is supported in projections and my handwritten mapping code wasn't traversing circular.  

I think it is safe to assume circular mapping is not a common thing. DTOs usually end up serialized where circular referencing is a big NO there.  JSON.net actually throws exceptions unless you explicitly tell it to ignore circular references. I think you should stop the operations that creates infinite loop and warn the user that types are circular referenced and should be manually mapped. That would be enough.

Sorry to hit you with the edge case bug that quick :)

Thank you for the fantastic work!

**Comment by cezarypiatek** [comment]
Thanks for clarification. I've made an attempt of implementing this protection. A new version that should handle recursive models is available here https://ci.appveyor.com/api/buildjobs/7sddnmcwf2kp524d/artifacts/MappingGenerator%2FMappingGenerator%2FMappingGenerator.Vsix%2Fbin%2FRelease%2FMappingGenerator.vsix

I would be appreciate if you could test it.

**Comment by Serguzest** [comment]
It seems fine to me. 

I tested it both for recursion that occurs between immediate nodes and recursion that occurs with one level deeper traversal. It could detect it in both cases. Good job!

**Comment by cezarypiatek** [comment]
It's good to hear that. Thanks for your help and collaboration. The new version should be released through official channel in few minutes.
