### ISSUE TITLE
Inconsistent behaviour

### ISSUE THREAD

**Issue by bdaniel7** [cezarypiatek/MappingGenerator#142]
Thanks for this life saving nuget! :))

I'm using the nuget version with Rider. And in some situations it works, in some, it doesn't.
I use Alt + Enter.

It's ok.

![works](https://user-images.githubusercontent.com/215914/95991436-6f66dd80-0e35-11eb-8f36-c59bad95620e.png)

It should display the __Initialize with local variables__ and use the properties of the class.

![doesnt-work](https://user-images.githubusercontent.com/215914/95991440-70980a80-0e35-11eb-8a4b-5e9249eebb3b.png)

Also, it doesn't show the __Implement Clone method__ when I select/set the cursor on the class name.

**Comment by cezarypiatek** [comment]
Ad1. I need to check that, can you provide a sample solution?
Ad2. "Implement Clone metho" - I don't provide such functionality. You probably confused MappingGenerator with something else.

**Comment by bdaniel7** [comment]
Ad2. In the project wiki there is a paragraph
- __Generate ICloneable interface implementation__ - with a gif.

**Comment by cezarypiatek** [comment]
I don't see any problem with "Implement clone" options, works fine in any "space" configuration. 

![5eAmDaeUDq](https://user-images.githubusercontent.com/7759991/96020241-00e24980-0e4e-11eb-8d3c-c386edb556c7.gif)


Tested on Rider 2020.2.1
![image](https://user-images.githubusercontent.com/7759991/96020193-ee681000-0e4d-11eb-8e80-7f01568f80aa.png)

**Comment by cezarypiatek** [comment]
"Initialize with local values" - this action is using only local variables and method parameters. It's not using enclosing type members. This is the current behavior.

**Comment by bdaniel7** [comment]
Ok, I'm getting the menu when I have the cursor on the class name. Previously I had the cursor just at the end of class name.
But when I try to invoke the action, the IDE freezes. I have to close it from Task Manager. I'm using Rider 2020.2.4

**Comment by cezarypiatek** [comment]
How large is your solution and how complex is the cloned class?

**Comment by bdaniel7** [comment]
Some classes have around 750 lines, including curly braces and empty lines. Other classes have 45 or 75 lines, with just 2 to 10 properties.

**Comment by cezarypiatek** [comment]
does it hang on that sample solution too?

**Comment by bdaniel7** [comment]
Nope.

**Comment by cezarypiatek** [comment]
So I guess this is due to solution size. This problem is already reported here https://github.com/cezarypiatek/MappingGenerator/issues/115

I tried to profile MappinGenerator several times but I wasn't able to find anything suspicions. Without real example I'm not able to diagnose this problem.

**Comment by bdaniel7** [comment]
Alright, in the meantime I will try a workaround.

**Comment by cezarypiatek** [comment]
@bdaniel7 might I ask you to test it once again using v1.19.452?

**Comment by bdaniel7** [comment]
First, the compilation for the entire solution become waaay slower - when using ```dotnet watch run```.
Even when just a file is modified.
Which makes the CPU and the fans go crazy...
Then, I got all kinds of warnings that I didn't get before, and that I had to disable with <NoWarn>VSTHRD200,VSTHRD103,VSTHRD002,VSTHRD110,VSTHRD003</NoWarn>.

**Comment by cezarypiatek** [comment]
Thanks for quick reply. It's my mistake, the analyzers were referenced incorrectly, shold be fixed in v1.19.454

**Comment by cezarypiatek** [comment]
I'm closing this issue. The case with performance can be tracked here #115
