### ISSUE TITLE
Use the existing instance instead of creating a new one

### ISSUE THREAD

**Issue by ducmerida** [cezarypiatek/MappingGenerator#146]
## With the following code
```
public class PersonEntity
{
     public int Id { get; set; }
     public string FirstName { get; set; }
     public string LastName { get; set; }
}

public class PersonModel
{
     public int Id { get; set; }
     public string FirstName { get; set; }
     public string LastName { get; set; }
}

MyPersonService.cs
public async Task SaveAsync(PersonModel model)
{
   var entity = (await repository.GetAsync(model.Id)) ?? new PersonEntity();

   entity = model;///Cannot convert implicit type => Generate explicit conversion

   repository.Save(entity)
}

```

## I get the current result

```
MyPersonService.cs

public async Task SaveAsync(PersonModel model)
{
   var entity = (await repository.GetAsync(model.Id)) ?? new PersonEntity();

   entity = new PersonEntity
   {
        Id = model.Id,
        FirstName = model.FirstName,
	LastName = model.LastName
   };

   repository.Save(entity)
}
```

## I would like to get the folowing code
```
MyPersonService.cs

public async Task SaveAsync(PersonModel model)
{
   var entity = (await repository.GetAsync(model.Id)) ?? new PersonEntity();

   entity.Id = model.Id;
   entity.FirstName = model.FirstName;
   enity.LastName = model.LastName;

   repository.Save(entity)
}
```

**Comment by cezarypiatek** [comment]
Hi @ducmerida 
Thanks for bringing this use case. I can implement it, maybe even as a speared code fix.

In the meantime please consider supporting MappingGenerator project

**Comment by ducmerida** [comment]
@cezarypiatek thanks, I've already bought you a cookee but I will buy 2 more :)

**Comment by cezarypiatek** [comment]
ohh I didn't know that, I though that the first coffee was from a guy who requested #145. Anyway, I truly appreciate.

**Comment by cezarypiatek** [comment]
@ducmerida 

Here's a pre-release version that contains requested feature. Would you mind testing it and letting me know if it works as you expected?

VSIX:
https://ci.appveyor.com/api/buildjobs/to5ovokll01202r2/artifacts/MappingGenerator%2FMappingGenerator%2FMappingGenerator.Vsix%2Fbin%2FRelease%2FMappingGenerator.vsix

Nuget:
https://ci.appveyor.com/api/buildjobs/to5ovokll01202r2/artifacts/MappingGenerator%2FMappingGenerator%2FMappingGenerator%2Fbin%2FRelease%2FMappingGenerator.1.19.460.nupkg

**Comment by ducmerida** [comment]
@cezarypiatek thanks a lot for you quick implementation, I've tried the VSIX and it doesn't work, you have a little error on your code, I leave you a comment on your PR #147

**Comment by cezarypiatek** [comment]
Thanks for testing and spotting the mistake. Should be fixed now.

**Comment by ducmerida** [comment]
@cezarypiatek thanks, i confirm that this last VSIX works perfectly :)

**Comment by cezarypiatek** [comment]
Many thanks for requesting this feature, seems to be very useful, and for your collaboration. I will release an official version today later.

**Comment by cezarypiatek** [comment]
An official version 1.20.463 with this feature has been released
