### ISSUE TITLE
Suggestion: Scaffold invocation on multiple lines. 

### ISSUE THREAD

**Issue by fiseni** [cezarypiatek/MappingGenerator#149]
The existing feature is really great and useful. Any chance we can get some styling while scaffolding?
Something similar to the usage below. Basically, the ability to scaffold arguments on separate lines.

```
public AddressDto GetAddress1()
{
    return new AddressDto(street: "lorem ipsum", city: "lorem ipsum", country: "lorem ipsum");
}

public AddressDto GetAddress2()
{
    return new AddressDto
    (
        street: "lorem ipsum",
        city: "lorem ipsum",
        country: "lorem ipsum"
    );
}
```

I'm not familiar with VS extension eco-system, so I have no idea if this is a trivial thing, or if it requires substantial effort.
I just think would be a really nice feature to have. At least in my perspective :)

**Comment by cezarypiatek** [comment]
I will try to look at this over the weekend.

**Comment by cezarypiatek** [comment]
The premium version contains an advanced method invocation scaffolder that allows for this kind of formatting.

![image](https://user-images.githubusercontent.com/7759991/149652533-5089aa2a-6ea6-4a3d-b3fd-4b9e58e2d468.png)


More details about this feature in doc https://docs.mappinggenerator.net/invocation-scaffolding/invocation-scaffolder/
The Premium license can be acquired on the official webpage https://mappinggenerator.net/
If you have any other remarks or suggestions please report them here https://github.com/cezarypiatek/MappingGeneratorIssueTracker
