### ISSUE TITLE
VSCode extention ?

### ISSUE THREAD

**Issue by LucaGabi** [cezarypiatek/MappingGenerator#154]
Hi, this article here states that this tool works also with vscode:

https://guidnew.com/en/blog/mapping-generator-design-time-alternative-to-automapper/

![image](https://user-images.githubusercontent.com/37976898/103270788-74ade000-49c1-11eb-9509-8c191cf8abd9.png)

I that true ?

**Comment by cezarypiatek** [comment]
Hi @LucaGabi

If you are interested in using MappingGenerator with VSCode then please take a look at
https://github.com/cezarypiatek/MappingGenerator#vscode

Any feedback is welcome.
