### ISSUE TITLE
ValueCollection appears to cause crash on Quick Action

### ISSUE THREAD

**Issue by antmeehan** [cezarypiatek/MappingGenerator#161]
**Mapping Generator Version**
v1.21.15

**Mapping Generator distribution**
VSExtension

**IDE type and version**
Microsoft Visual Studio Professional 2019
Version 16.8.4
VisualStudio.16.Release/16.8.4+30907.101

**Describe the incorrect behavior**
When invoking the Quick Action menu on a CS0029 C# Cannot implicitly convert type squiggle which is a `Dictionary<T,K>.ValueCollection` the MappingGenerator extension crashes with the following stack trace:

> System.IndexOutOfRangeException : Index was outside the bounds of the array.
>    at MappingGenerator.Mappings.MappingHelper.GetElementType(ITypeSymbol collectionType)
>    at async MappingGenerator.Mappings.MappingEngine.MapCollectionsAsync(<Unknown Parameters>)
>    at async MappingGenerator.Mappings.MappingEngine.TryToCreateMappingExpression(<Unknown Parameters>)
>    at async MappingGenerator.Mappings.MappingEngine.MapExpression(<Unknown Parameters>)
>    at async MappingGenerator.Mappings.MappingEngine.MapExpression(<Unknown Parameters>)
>    at async MappingGenerator.Features.CodeFixes.ExplicitConversionCodeFixProvider.GenerateExplicitConversion(<Unknown Parameters>)
>    at async Microsoft.CodeAnalysis.CodeActions.CodeAction.GetChangedSolutionAsync(<Unknown Parameters>)
>    at async Microsoft.CodeAnalysis.CodeActions.CodeAction.ComputeOperationsAsync(<Unknown Parameters>)
>    at async Microsoft.CodeAnalysis.CodeActions.CodeAction.GetPreviewOperationsAsync(<Unknown Parameters>)
>    at async Microsoft.CodeAnalysis.Editor.Implementation.Suggestions.SuggestedAction.GetPreviewResultAsync(<Unknown Parameters>)
>    at async Microsoft.CodeAnalysis.Editor.Implementation.Suggestions.SuggestedActionWithNestedFlavors.<>c__DisplayClass11_0.<GetPreviewAsync>b__0(<Unknown Parameters>)
>    at async Microsoft.CodeAnalysis.Extensions.IExtensionManagerExtensions.PerformFunctionAsync[T](<Unknown Parameters>)

Here is some example code to reproduce:

```csharp
public class Source { }
public class Destination { }

public IEnumerable<Destination> Example(Dictionary<string, Source> source)
{
	return source.Values;
}
```

**Describe the expected behavior**
Would expect either no suggestion from MappingGenerator, or even better it can create mapping from the `ValueCollection`.

**Screenshots**
![image](https://user-images.githubusercontent.com/9822503/105184632-8884d600-5b6a-11eb-81e0-0a58741926a7.png)

![image](https://user-images.githubusercontent.com/9822503/105184010-cdf4d380-5b69-11eb-89fa-80bb3cd0ff7b.png)

**Comment by cezarypiatek** [comment]
Hi @antmeehan 

This should be fixed in v1.22.  Would you mind testing the fix and letting me know it that works for you as expected?


Please also consider supporting MappingGenerator project. Thanks!

**Comment by antmeehan** [comment]
Thanks @cezarypiatek for the fast response! I'm very impressed with your DevOps process too. 

The fix stops the crash now, but the mapping doesn't occur as I would expect. Eg.

```csharp
public class Source
{
	public string A { get; set; }
}

public class Destination
{
	public string A { get; set; }
}

public IEnumerable<Destination> Example(Dictionary<string, Source> source)
{
	return source.Values;
}
```

gets changed to:

```csharp
public IEnumerable<Destination> Example(Dictionary<string, Source> source)
{
	return source.Values.Select(sourceValue => new Destination());
}
```

But I would expect:

```csharp
public IEnumerable<Destination> Example(Dictionary<string, Source> source)
{
	return source.Values.Select(sourceValue => new Destination()
	{
		A = sourceValue.A
	});
}
```

**Comment by cezarypiatek** [comment]
HI @antmeehan 

Apologies, my mistake. Please check v1.22.1 (should be released shortly)
