### ISSUE TITLE
Visual Studio Performance slowing down

### ISSUE THREAD

**Issue by Garozh** [cezarypiatek/MappingGenerator#165]
**Mapping Generator Version**
[Current]

**Mapping Generator distribution**
VSExtension/NugetPackage

**IDE type and version**
Visual Studio 2019 16.8.4

**Resharper version**
2020.3.2

Hey there,

first of all that's a really nice expansion i love to use. But when I'm using the Expansion, my Visual Studio is slowing down hard. The editor and menus can't be used properly anymore bcs of the lag that's happening. When I deactivate the expansion it's working fine. 

The slowdown happens after the first auto generated code I generate with the expansion. A Restart of Visual studio will also make it work again.

Any hints, configurations to make. Anyone else noticing that behaviour?

**Comment by cezarypiatek** [comment]
Duplicate #115
