### ISSUE TITLE
Add simplified object initialization

### ISSUE THREAD

**Issue by ungradge** [cezarypiatek/MappingGenerator#18]
If code style rule  "IDE0017 Object initialization can be simplified" enabled (default) in VS, generated mapping code cause the warning occurrence. Maybe it worth to consider implement simplified object initialization or added this feature as an option in the extension configuration.
![map_001](https://user-images.githubusercontent.com/28894060/39429639-274a4b64-4c94-11e8-9faf-8d1213445929.png)

**Comment by cezarypiatek** [comment]
This is one of the must have feature. Because the mapping can be very complex (with nested object) is's not so easy to implement. Probably it requires refactoring of MappingGenerator class.

**Comment by cezarypiatek** [comment]
Available in https://github.com/cezarypiatek/MappingGenerator/releases/tag/1.3.116
@ungradge I would be appreciate if you could check this new mapping option and let me know if everything works fine.
