### ISSUE TITLE
Support for Visual Studio Community 2015

### ISSUE THREAD

**Issue by foxip** [cezarypiatek/MappingGenerator#2]
Hi, I have a question. Can MappingGenerator be installed on Visual Studio Community 2015? 
I got the following installation error:

1-3-2018 11:22:45 - Microsoft VSIX Installer
1-3-2018 11:22:45 - -------------------------------------------
1-3-2018 11:22:45 - Initializing Install...
1-3-2018 11:22:45 - Extension Details...
1-3-2018 11:22:45 - 	Identifier         : MappingGenerator.de964118-68da-48b7-9b74-0bf8a2c5bfa3
1-3-2018 11:22:45 - 	Name               : MappingGenerator
1-3-2018 11:22:45 - 	Author             : cepi
1-3-2018 11:22:45 - 	Version            : 1.0
1-3-2018 11:22:45 - 	Description        : Roslyn based code fix provider that allows to generate mapping code in design time.
1-3-2018 11:22:45 - 	Locale             : en-US
1-3-2018 11:22:45 - 	MoreInfoURL        : 
1-3-2018 11:22:45 - 	InstalledByMSI     : False
1-3-2018 11:22:45 - 	SupportedFrameworkVersionRange : [4.5,)
1-3-2018 11:22:45 - 
1-3-2018 11:22:45 - 	SignatureState     : Unsigned
1-3-2018 11:22:45 - 	Supported Products : 
1-3-2018 11:22:45 - 		Microsoft.VisualStudio.Community
1-3-2018 11:22:45 - 			Version : [15.0,)
1-3-2018 11:22:45 - 
1-3-2018 11:22:45 - 	References         : 
1-3-2018 11:22:45 - Signature Details...
1-3-2018 11:22:45 - 	Extension is not signed.
1-3-2018 11:22:45 - 
1-3-2018 11:22:45 - Searching for applicable products...
1-3-2018 11:22:48 - Found installed product - Microsoft Visual Studio Professional 2013
1-3-2018 11:22:48 - Found installed product - Microsoft Visual Studio 2013 Shell (Integrated)
1-3-2018 11:22:48 - Found installed product - Microsoft Visual Studio Community 2015
1-3-2018 11:22:48 - Found installed product - Microsoft Visual Studio 2015 Shell (Integrated)
1-3-2018 11:22:48 - Found installed product - Global Location
1-3-2018 11:22:48 - Found installed product - ssms
1-3-2018 11:22:48 - VSIXInstaller.NoApplicableSKUsException: This extension is not installable on any currently installed products.
   at VSIXInstaller.App.InitializeInstall(Boolean isRepairSupported)
   at VSIXInstaller.App.InitializeInstall()
   at System.Threading.Tasks.Task.InnerInvoke()
   at System.Threading.Tasks.Task.Execute()

**Comment by cezarypiatek** [comment]
I'm not aware of any limitation that could prevent from installing in Visual Studio 2015. I forgot that VS 2015 has version 14.0 not 15.0 so probably changing supported minimal version in VSIX from 15.0 to 14.0 manifest should fix the issue

**Comment by foxip** [comment]
Hi, i changed it to 14.0 and it does install now.

**Comment by foxip** [comment]
But the extension does not seem to work.

**Comment by cezarypiatek** [comment]
I found the old laptop with VS2015 Community and I can confirm that this analyzer unfortunately is not working with this version of VS. This is probably due to the lack of support for current Roslyn version in VS2015. I have no idea how to support both versions of VS without creating another solution based on older  version of compiler SDK. I will keep this issue open but help is needed.
