### ISSUE TITLE
Installed VS Extension... and now what?

### ISSUE THREAD

**Issue by alprinias** [cezarypiatek/MappingGenerator#24]
Hi,

I am trying to understand how to use your extension. I installed the vsix in my VS 2017 community and I can see it in my Extensions and Updates (v. 1.3.125). And now? What do I have to do to use it? I cannot see any "Generate Mapping ..." when I hover the yellow light bulbs on the left side of my code window. What am I missing?

Best,
Alex

**Comment by cezarypiatek** [comment]
Hi

By default MappingGenerator functions should be available in `light bulbs` or by pressing `ctr`+`.`
Could you provide a code that your are trying to treat with MappingGenerator?

**Comment by alprinias** [comment]
Hi Cezary, thanks for your answer. After installing the extension and a couple of VS restarts, it wasn't showing. After that, I installed a VS update (15.7.5) and now it shows! Who knows what it was...
Thank you !
Alex

**Comment by cezarypiatek** [comment]
I'm happy to hear that everything works. It's not the first time when one update of VS breaks Roslyn analyzers and another one fix it.
