### ISSUE TITLE
Clone object mapping

### ISSUE THREAD

**Issue by phoenix172** [cezarypiatek/MappingGenerator#31]
It would be nice if there was a straightforward way to create a clone. I know that currently that can be accomplished by creating a mapping that takes and returns the same object, and after that alt-enter -> explicit mapping, but I was wondering if it wouldnt be better to directly generate explicit mapping in the above scenario. Writing a mapping method that takes and returns the same type doesn't really make sense in any other case, unless you want to clone (and maybe modify slightly) the passed object.

P.S: Love the tool. Saves me from writing boring code.

P.P.S: Sorry for overwhelming you with issues :D

**Comment by cezarypiatek** [comment]
Great idea, I like it. I will try to implement it.

**Comment by cezarypiatek** [comment]
Here is my first attempt of implementing refactoring that generate clone method. Would you mind to test it and give me some feedback about results? Version with this experimental feature is available here 

https://ci.appveyor.com/api/buildjobs/saey15a33qqlgh92/artifacts/MappingGenerator%2FMappingGenerator%2FMappingGenerator.Vsix%2Fbin%2FRelease%2FMappingGenerator.vsix

![clone_sample](https://user-images.githubusercontent.com/7759991/44867726-f45c0080-ac88-11e8-87e9-feed8242af79.gif)

**Comment by phoenix172** [comment]
Yeah, sorry been away for a while. Gonna test it when I get to work.

**Comment by phoenix172** [comment]
Ok, I tested the new update. It seems good with a few notes:

1. When you try to generate clone method for class that has a base type, the ICloneable interfaces gets placed before the base type, which generates a compile error. Manually fixing it is not difficult, but I think it would be quite easy for you to correct the behavior.

![2018-09-10_15-16-54](https://user-images.githubusercontent.com/11656684/45297071-d1451280-b50c-11e8-84c3-8c1a08907d88.gif)

2.  I think it would be useful to be able to generate a clone method simply by defining a method with return type same as the owning type, and then executing the code refactoring, without having to implement ICloneable.

Something like this:
![2018-09-10_15-21-29](https://user-images.githubusercontent.com/11656684/45297183-3862c700-b50d-11e8-89c4-82bbde154442.gif)

The name of the method need not be constrained to clone. It was just an example.

3. Another useful and maybe not difficult to implement feature would be generating object cloning code , when you define a method with a single parameter that is the same type as the return type.
Currently in this scenario "return parameter;" gets generated.
I think it would be nice if instead it generated a clone method.

Something like this:
![2018-09-10_15-25-15](https://user-images.githubusercontent.com/11656684/45297352-c2ab2b00-b50d-11e8-85b7-3390ac3b23e2.gif)

But instead of generating "return parent;", it would generate code for cloning the object.
I don't think anyone would need a refactoring that generates a method that just returns its parameter. The above suggestion is far more useful, and I think it would be what the user would expect to happen.

I hope the above feedback helps. Sorry for the late reply and cheers for the feature. :) 👍

**Comment by cezarypiatek** [comment]
Great feedback, thanks a lot!!! I will try to implement your suggestions.

**Comment by cezarypiatek** [comment]
@phoenix172 
According to pt 3 How the complex properties should be mapped: rewriting property by property even if the object implement `ICloneable` interface 

```cs
        public User Clone(User u)
        {
            return new User()
            {
                FirstName = u.FirstName,
                LastName = u.LastName,
                Age = u.Age,
                ComplexProperty = new ComplexObject{
                        Prop1 = u.ComplexProperty.Prop1,
                        Prop2 = u.ComplexProperty.Prop2
               }
            };
        }
```

or call `Clone()` method if it's accessible?

```cs
        public User Clone(User u)
        {
            return new User()
            {
                FirstName = u.FirstName,
                LastName = u.LastName,
                Age = u.Age,
                ComplexProperty = u.ComplexProperty.Clone(),
            };
        }
```

**Comment by phoenix172** [comment]
I think utilizing the Clone method if ICloneable is implemented sounds reasonable. After all you are cloning the object and the object is offering a way to clone itself. With that said though, something like an "to explicit mapping" refactoring will be nice to have on the Clone method call.

**Comment by cezarypiatek** [comment]
Here's the new version that implements all your suggestions https://ci.appveyor.com/api/buildjobs/q2luj7o5s5jstwsw/artifacts/MappingGenerator%2FMappingGenerator%2FMappingGenerator.Vsix%2Fbin%2FRelease%2FMappingGenerator.vsix

Any feedback is welcome as always ;)

**Comment by cezarypiatek** [comment]
@phoenix172 sorry for bothering you, but I'm not sure you got the notification about last update. I would like to release this feature in few days.

**Comment by cezarypiatek** [comment]
Thanks for information and your time. I'm really appreciate.
