### ISSUE TITLE
Support for Expression<Func<in T, out TResult>>

### ISSUE THREAD

**Issue by lindeberg** [cezarypiatek/MappingGenerator#34]
Hey! Awesome project. I too thought automapper got in the way in a large project.

I'd like to request a further feature. I'm working a lot with IQueryable projections and within those c# methods aren't really supported as far as I know?

So I make a few mapping expressions like this:
```
 public static Expression<Func<Core.Models.Entities.Member, QueryResult.Member>> Map = member => new Member
{
                FirstName = member.FirstName
};
```

which I then use like this:
```
var items = members
                .Select(QueryResult.Member.Map)
                .ToList();
```

I cannot find support for this feature atm and would really like to see it implemented :)

**Comment by cezarypiatek** [comment]
Hi

I'm not sure if I'm understanding requested feature correctly. For me it looks like #14 which has been implemented already. If you expect something different please provide a sample code before and after transformation for better understanding.

**Comment by lindeberg** [comment]
That's exactly what I was requesting, haha, awesome it's already implemented! Sorry, I just couldnt find it, I didn't which was the right spot to put the cursor i guess. Thanks!!

**Comment by cezarypiatek** [comment]
No problem, I'm glad I could help you out. I've updated `readme` with example for this functionality.
