### ISSUE TITLE
analyze code for added properties

### ISSUE THREAD

**Issue by ignatandrei** [cezarypiatek/MappingGenerator#4]
Support that you have generated code. Then you add another properties. And you want those generated too. And remember where you should add

**Comment by cezarypiatek** [comment]
Hi
I'm not exactly sure what you wan to accomplish. Could you provide example use case and the code that should be generated for it?

**Comment by cezarypiatek** [comment]
Hi
Actually I was thinking about something like that at the beginning bu finally I decided not implement that.  Introducing this feature will require marking somehow generated code and tracking the changes in the source and destination types. This will introduce some kind of magic to your project and impose using this tool by every team member. In most cases the generated code probably needs additional adjustments which could also increase complexity of such feature (you need to somehow determine which part of the generated code was manually modified and merge with the new version - probably impossible to implementation)

The main goal of this tool is to support creating maintainable code (by fast scaffolding) not to maintain it. 

By the way, I'm really curious what is you more detailed vision of this functionality? Maybe I'm wrong and this could be introduced without any magic in the project.

**Comment by cezarypiatek** [comment]
It looks like there is no will for collaboration only features demanding. Issue closed.

**Comment by OmiCron07** [comment]
I will be interested to have errors (solution can't compile) when there are missing properties in mappers. Do you think that you can take inspiration from this: https://github.com/angularsen/roslyn-analyzers#sample

**Comment by cezarypiatek** [comment]
Looks interesting. Probably easy to implementation without  tracking changes. I created a new issue for that #7
