### ISSUE TITLE
Inherited properties not generating

### ISSUE THREAD

**Issue by aeslinger0** [cezarypiatek/MappingGenerator#44]
I have an entity that inherits `Microsoft.AspNet.Identity.EntityFramework.IdentityUser` from `packages\Microsoft.AspNet.Identity.EntityFramework.2.2.1\lib\net45\Microsoft.AspNet.Identity.EntityFramework.dll`. The properties in my entity get mapped, but not the ones from `IdentityUser` such as "Email". Here's what the method starts out as:

```
public static ApplicationUserEntity ToEntity(this UserModel model)
{
}
```

**Comment by cezarypiatek** [comment]
Thanks for reporting. There is a problem with checking visibility of fields in types which are not declared in the source code. I will need to investigate that.  I will let you know when I find the solution.

**Comment by cezarypiatek** [comment]
@aeslinger0 Here's a new package version that should contains fix for this issue https://ci.appveyor.com/api/buildjobs/mwll3jx0755e5qxv/artifacts/MappingGenerator%2FMappingGenerator%2FMappingGenerator.Vsix%2Fbin%2FRelease%2FMappingGenerator.vsix

Would you mind to test it and confirm if everything is working as you expected?

**Comment by aeslinger0** [comment]
Sorry, I haven't had a chance to test it yet. I will as soon as I'm able to.

**Comment by aeslinger0** [comment]
That appears to work, thanks.

**Comment by cezarypiatek** [comment]
Thanks for testing. It should be released in few  days.
