### ISSUE TITLE
Can't get Mapping options in Roslyn menu

### ISSUE THREAD

**Issue by brrbtr** [cezarypiatek/MappingGenerator#50]
I have ReSharper installed, but disabled. Restarted VS 2017. Still no Generate Mapping Code in the Roslyn menu. I verified that the extension appears to be installed. What is required for the Generate Mapping Code to show up ?

**Comment by cezarypiatek** [comment]
Hi

What exactly version of VS 2018 do you have installed?  Did you restart VS after installing the extension?
Roslyn menu should be triggered with `ctr + .` shortcut.

**Comment by brrbtr** [comment]
VS Enterprise 2017 (15.8.9)
Yes, restarted.
Here's what I see:
![image](https://user-images.githubusercontent.com/5473194/48422293-ff6ceb80-e723-11e8-88b6-fdf1b8feec78.png)

**Comment by cezarypiatek** [comment]
Have you tried with the code is correct? Your method signature is invalid - no identifier for method parameter.

**Comment by brrbtr** [comment]
Yes. I had. (I just tried to spin up an example really quickly and forgot to finish...) In the meantime, my system got updated and rebooted for me (without permission, of course). Now, it seems to be working just fine. Sorry for the bother.

**Comment by cezarypiatek** [comment]
No problem, good to know that even bugs in OS can break Roslyn analyzers.

**Comment by pug-pelle-p** [comment]
I still experience this problem, is there any known fix for this?

**Comment by cezarypiatek** [comment]
@pug-pelle-p please update VS 2017 to the newest version and restart your computer

**Comment by paluch82** [comment]
Hi, 
I have Resharper 2018.3.1 and Visual Studio 2017 version 15.9.4. Unfortunately I cannot get the Mapping Generator menu. I tried to restart computer but this didn't help. Do you know how  to fix the issue?

**Comment by cezarypiatek** [comment]
@paluch82 please provide your code where you expect MappingGenerator options.

**Comment by paluch82** [comment]
Hi,

Here is my sample code:
`public class Test
    {
        public class ClassA
        {
            public string Name { get; set; }
            public int Value { get; set; }
        }

        public class ClassB
        {
            public string Name { get; set; }
            public int Value { get; set; }
        }

        private ClassB Map(ClassA a)
        {

        }
    }`
The issue is related with Resharper because when I disable it MappingGenerator options shows up.

**Comment by paluch82** [comment]
This resolved the issue. Now it works like a charm. Thanks.

**Comment by Havret** [comment]
I think this should be included in project's ReadMe.
