### ISSUE TITLE
404 for post in readme

### ISSUE THREAD

**Issue by cocowalla** [cezarypiatek/MappingGenerator#56]
Your Automapper post, mentioned in the readme, is now a 404:

[https://cezarypiatek.github.io/post/why-i-dont-use-automapper/](https://cezarypiatek.github.io/post/why-i-dont-use-automapper/)

**Comment by cezarypiatek** [comment]
Hi @cocowalla 

It looks like there is problem with github pages. Thanks for information. I'll investigate it later.

**Comment by cocowalla** [comment]
All good now (y)
