### ISSUE TITLE
Generate mapping from generics

### ISSUE THREAD

**Issue by OmiCron07** [cezarypiatek/MappingGenerator#6]
My converters are generics and your generator generate empty methods with these converters.

![code](https://user-images.githubusercontent.com/31325575/37430122-9c253668-27a7-11e8-8b85-9c4cb3e151c7.jpg)

Do you think you can do something about my scenario?

**Comment by cezarypiatek** [comment]
I've never tried with generic types. I need to investigate that.

**Comment by cezarypiatek** [comment]
I managed to implement that. It's scheduled for the next release. You can test current implementation installing vsix from commit build https://ci.appveyor.com/api/buildjobs/iqexgx6p8djryph5/artifacts/MappingGenerator%2FMappingGenerator%2FMappingGenerator.Vsix%2Fbin%2FRelease%2FMappingGenerator.vsix

**Comment by OmiCron07** [comment]
Nice, it's working with my scenario. Thank you!
