### ISSUE TITLE
Options won't show up

### ISSUE THREAD

**Issue by lindeberg** [cezarypiatek/MappingGenerator#62]
Visual Studio 15.9.5

Both objects have a bunch of identical properties.

https://gyazo.com/504fbb92e58c062bdc2e91fa9ab1083d

**Comment by cezarypiatek** [comment]
Hi

Please try suggestion from this issue https://github.com/cezarypiatek/MappingGenerator/issues/50

Let me know if that help.

**Comment by lindeberg** [comment]
Worked! Thanks, you rock!
