### ISSUE TITLE
Support for Visual Studio 2019 beta

### ISSUE THREAD

**Issue by bseng** [cezarypiatek/MappingGenerator#66]
Hi,

First of all congratulate on this amazing plugin!

I just tried to install in visual studio 2019 it said there's a pre-requisite and can't be installed.

Do you know what else do I need to install before installing this plugin?

Thanks,

**Comment by cezarypiatek** [comment]
Hi

I haven't had occasion to test it on VS2019. I guess the VSIX manifest should be adjusted to make it work with VS2019.  https://github.com/cezarypiatek/MappingGenerator/blob/master/MappingGenerator/MappingGenerator/MappingGenerator.Vsix/source.extension.vsixmanifest

I will check that later and let you know if I'm able to release version with VS2019 support.

**Comment by cezarypiatek** [comment]
I've made a few adjustment to the extension manifest. @bseng would you mind to test this version and tell me if everything is working ok on VS2019? 
Here's the package with fixed manifest https://ci.appveyor.com/api/buildjobs/gf0jkfskdol78eru/artifacts/MappingGenerator%2FMappingGenerator%2FMappingGenerator.Vsix%2Fbin%2FRelease%2FMappingGenerator.vsix

**Comment by bseng** [comment]
It installs on 2019 beta and works great! Thanks for the quick response.

**Comment by cezarypiatek** [comment]
Thanks for the feedback
