### ISSUE TITLE
[Feature request] - Code generation for equals override

### ISSUE THREAD

**Issue by bseng** [cezarypiatek/MappingGenerator#67]
Hi,

Can we have another generate options that generate a compare function. 

similar to https://github.com/GregFinzer/Compare-Net-Objects but without the reflection magic.

Thanks

**Comment by cezarypiatek** [comment]
Hi

Please check my another plugin https://github.com/cezarypiatek/DDDToolbox which is able to generate Equals method and comparison operators.  Please let me know if that meets your requirements.

**Comment by cezarypiatek** [comment]
@bseng did you try DDDToolbox? Does this issue still matter?

**Comment by bseng** [comment]
yeah that plugin looks good. Thanks~
