### ISSUE TITLE
Just not working in my VS2017 Pro/Community

### ISSUE THREAD

**Issue by whopkinscom** [cezarypiatek/MappingGenerator#70]
Hi Cezary,

I've used your plug-in successfully in a previous contract but though I've installed it, it just doesn't present itself. It shows as installed within the VS Extensions & Updates but that's as much as I get. Any hints to try to resolve it?

I'm running VS2017 Vsn 15.9.7 and get the same issue on the latest Community Edition

Cheers,

Will

**Comment by cezarypiatek** [comment]
Hi
Please check the hints from the #50 and let me know if this solved the issue.

**Comment by whopkinscom** [comment]
Thanks. It was the resharper settings re. the lightbulb.

Nice one,
