### ISSUE TITLE
Creating object in factory method

### ISSUE THREAD

**Issue by rmaziarka** [cezarypiatek/MappingGenerator#76]
Hello Cezary,

I tried to use your extension and found out that it lacks one functionality that I wanted to use. 

From DTO / command class I want to create an entity. For example from CreateProductCommand I run ToProduct method.:
```csharp
    public class CreateProductCommand
    {

        public string Name { get; set; }

        public decimal Price { get; set; }

        public Category Category { get; set; }

        public Tag[] Tags { get; set; }

        public Product ToProduct()
        {
            return new Product(); //<----
        }
    }

    public class Product
    {
        public Product(string name, decimal price, Category category, Tag[] tags)
        {
            Id = new Guid();
            Name = name;
            Price = price;
            Category = category;
            Tags = tags;
        }

        public Guid Id { get; private set; }

        public string Name { get; private set; }

        public decimal Price { get; private set; }

        public Category Category { get; private set; }

        public Tag[] Tags { get; private set; }
    }
```
Would be able to provide auto-generating data to this constructor? Or maybe where should I find such option in the extension to try to add it on my own.

**Comment by cezarypiatek** [comment]
Unfortunately this scenario is not currently supported but I think it looks easy to implement it. I will try to add this later.

**Comment by cezarypiatek** [comment]
Here's the version that contains an implementation of this feature https://ci.appveyor.com/api/buildjobs/pnh37mqxjxakl3ge/artifacts/MappingGenerator%2FMappingGenerator%2FMappingGenerator.Vsix%2Fbin%2FRelease%2FMappingGenerator.vsix

@rmaziarka Would you mind to test it and let me know if everything is working as expected?

![issue76](https://user-images.githubusercontent.com/7759991/56824410-bbdfe700-6856-11e9-9e32-100734d2147f.gif)

**Comment by rmaziarka** [comment]
Works great, thanks :)

**Comment by cezarypiatek** [comment]
An official version with this feature was released Please install version of the official channel https://marketplace.visualstudio.com/items?itemName=54748ff9-45fc-43c2-8ec5-cf7912bc3b84.mappinggenerator
