### ISSUE TITLE
Nullable enum to int?

### ISSUE THREAD

**Issue by OmiCron07** [cezarypiatek/MappingGenerator#89]
I generated the following mapping :

````csharp
bendingTypeDetail = new BendingTypeDetail
                    {
                      TypeNumber = args.BendingTypeDetail.TypeNumber,
                      Definition = (int) args.BendingTypeDetail.Definition,
                      Threads = new int?(value: (int) args.BendingTypeDetail.Threads.Value),
                    };
````

The field `Definition` is an enum and it has been converted right in an int. But the conversion of the field `Threads`, which is a nullable enum converted to nullable int, is invalid and will likely generate a null exception.

Should has been `Threads = (int?) args.BendingTypeDetail.Threads`

**Comment by cezarypiatek** [comment]
You are right. Thanks for reporting this issue, I will try to fix it.

**Comment by cezarypiatek** [comment]
Here is a version with fix: https://ci.appveyor.com/api/buildjobs/r36cais6plavwx9c/artifacts/MappingGenerator%2FMappingGenerator%2FMappingGenerator.Vsix%2Fbin%2FRelease%2FMappingGenerator.vsix

Would you mind to test it and let me know if everything works according to your expectations?

**Comment by OmiCron07** [comment]
Seems all good 👍
