### ISSUE TITLE
Generate mapping returns new class without mapping - support for field mapping

### ISSUE THREAD

**Issue by imtrobin** [cezarypiatek/MappingGenerator#94]
Hi, is there some requirements of the map to work? I tried on my class, the "Generate mapping" part just shows new Class () without mapping the members. E.g.

```
public static  YYY   CreateYYYFromXXX (XXX x)
{
  // nothing is mapped
   returns new YYY ();
}
```

**Comment by cezarypiatek** [comment]
Hi @imtrobin,
Can you show YYY and XXX classes' definitions?

**Comment by imtrobin** [comment]
```
public class XXX
 {
        public string Name             = null;
        public string Description      = null;
        public HashSet <string> Hashes            = null;
}

public class YYY
    {
        public string ID    = null;
        public string Name             = null;
        public string Description      = null;

        public HashSet <string> Hashes            = null;
         public DateTime TimeCreated      = DateTime.MinValue;
}
```

**Comment by cezarypiatek** [comment]
Currently, MappingGenerator is using properties to determine the source and destination of mapping. Is there any particular reason why do you prefer fields over properties?

**Comment by imtrobin** [comment]
I see. I do not need c# properties get/set so I chose with simple fields since it is always public get/set

**Comment by cezarypiatek** [comment]
Since C# 3.0, when auto-implemented properties had been introduced, they should be a default choice.  
I can't see any specific reason why this language relict should be supported - of course, PR with the implementation of this functionality is welcome.

**Comment by imtrobin** [comment]
These are just simple classes to map rest requests. I do use properties in other places, where needed.  Will add it to my todo list. I presume you are using reflection so it should fairly easy to get member vars.

**Comment by cezarypiatek** [comment]
MappingGenerator is not using reflection. It's completely based on the  Roslyn and SyntaxTree analysis.

**Comment by imtrobin** [comment]
Oh bummer, not familiar with that.

**Comment by cezarypiatek** [comment]
I'm working on it but I can't promise when this will be released (I need to refactor a couple of things before to keep the codebase still maintainable).

**Comment by cezarypiatek** [comment]
A new version 1.16.393 with this feature has been released. @imtrobin could you test it and let me know if this works as expected?

**Comment by imtrobin** [comment]
Hi cezary, seems to be working well, thanks!
