### ISSUE TITLE
Mapping Nullable<bool> to NotNullable<bool>

### ISSUE THREAD

**Issue by KinNeko-De** [cezarypiatek/MappingGenerator#96]
Hello.
i tried your extension (Version 1.12.306) at some code. Its great but i think i have found a small issue.

I have a domain object with a nullable bool property and it should be mapped to not nullable bool dto.
This is bad design.. i know that :)

The MappingGenerator generates:

```
private Dto ToDomain(DomainObject domainobject)
{
   return new Dto(notnullableproperty: domainobject.nullableproperty.Value);
}
```
This code will fail when the nullableproperty is null.
I suggest to use `nullableproperty.GetValueOrDefault()` instead

**Comment by cezarypiatek** [comment]
Hi,

Current behavior was introduced intentionally. `NullReferenceException` should bring your attention to the discrepancy between the models . If you need a different behavior you should manually adjust generated code - that's the beauty of MappingGenerator.

**Comment by KinNeko-De** [comment]
Ok. I will get the atttention if i have a good unit test that does boundary tests :)

But i agree that a MappingGenerator is the best concept because you can easily change the code if the result is not what you expected.

**Comment by cezarypiatek** [comment]
@KinNeko-De  If you are using R#, you can configure static analysis to report all those situations as error

![image](https://user-images.githubusercontent.com/7759991/68784551-0717e680-063d-11ea-9222-6154a8792154.png)
