### ISSUE TITLE
Great work! Is there a road map for VS for Mac?

### ISSUE THREAD

**Issue by sabsuzuki** [cezarypiatek/MappingGenerator#98]
I'd like to thank you for the great extension. Very very useful! I'm wondering if is there a road map for a VS for Mac version.

**Comment by cezarypiatek** [comment]
Hi,
I have no idea how the support for Roslyn extensions look like on VS for Mac. I've asked about on https://gitter.im/dotnet/roslyn I will let know when get a response.

**Comment by cezarypiatek** [comment]
I haven't got any response so probably there is no option to easily port it. I'm closing this issue.
