### ISSUE TITLE
Support for F#

### ISSUE THREAD

**Issue by brikken** [cezarypiatek/MappingGenerator#99]
Any suggestions how to make this work for F#?

If that's not possible, any plans for supporting F# in the future? I'd be willing to help with implementation.

**Comment by cezarypiatek** [comment]
F# is not supported by the Roslyn (it has own compiler service) so the whole MappingGenerator should be totally rewritten to handle F#.  For now, there is no plans to do that but I leave this issue open to see if there are more people interested in this subject.
